" Settings
set backupdir=~/.vimfiles/backup/
set directory=~/.vimfiles/backup/
set fileencoding=utf-8
set hidden
set hlsearch
set incsearch
set ignorecase
set smartcase
let loaded_matchparen = 1

" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle "gmarik/vundle"

Bundle "mattn/emmet-vim"
Bundle "marijnh/tern_for_vim"
Bundle "tomtom/tlib_vim"
Bundle "nono/vim-handlebars"
Bundle "othree/html5.vim"
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "pangloss/vim-javascript"
Bundle "groenewege/vim-less"
Bundle "sickill/vim-pasta"
Bundle "garbas/vim-snipmate"
Bundle "honza/vim-snippets"

filetype plugin indent on 

" Visual
syntax on
set completeopt=menu
set gcr=a:blinkon1
set tabstop=4 
set softtabstop=0
set shiftwidth=4
set expandtab
set visualbell
set t_Co=256
call pathogen#infect()
colorscheme molokai
highlight ColorColumn ctermbg=darkgrey

" Powerline
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2

" Bindings
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>
map '' ciw'<C-r>"'<Esc>
" map d'' di'hPl2x
map "" ciw"<C-r>""<Esc>
" map d"" di"hPl2x
nmap <F5> :%y+<Return>
nmap <Tab> :b#<CR>
set pastetoggle=<F4>

" NERDTree configuration
let NERDTreeChDirMode=2
let NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$']
let NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$',  '\.bak$', '\~$']
let NERDTreeShowBookmarks=1
map <F3> :NERDTreeToggle<CR>

" Javascript
autocmd FileType javascript setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2 colorcolumn=80
autocmd FileType html,css,scss,less,sass setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" ctrlp
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn|meteor)$'

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal g'\"" | endif
endif

" Emmet
let g:user_emmet_install_global = 0
autocmd FileType html EmmetInstall
autocmd FileType html imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")

